name: reductstore-agent
version: 0.2.0
summary: ROS 2 recorder that streams topics into ReductStore
description: |
  ReductStore Agent is a ROS 2 recorder node that streams selected topics into
  ReductStore with configurable pipelines, compression, and labeling.
license: MIT
contact:
  - info@reduct.store
  - https://www.reduct.store/contact
issues: https://github.com/reductstore/reductstore_agent/issues
source-code: https://github.com/reductstore/reductstore_agent

base: core24
confinement: strict
grade: devel

components:
  replayer:
    type: standard
    summary: Optional rosbag replayer
    description: |
      Adds the rosbag_replayer node for replaying MCAP bag files.
      Install with: snap install reductstore-agent+replayer

plugs:
  configuration-read:
    interface: content
    content: configuration-read
    target: $SNAP_COMMON/configuration

parts:
  scripts:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/

  sample-config:
    plugin: dump
    source: config
    organize:
      'default.yml': share/reductstore_agent/config/params.yml

  agent:
    plugin: colcon
    source: .
    after: [scripts, sample-config]
    build-packages:
      - python3-venv
      - python3-pip
    stage-packages:
      - ros-jazzy-ros2cli
      - ros-jazzy-ros2run
      - ros-jazzy-rclpy
      - ros-jazzy-rosbag2-py
      - ros-jazzy-rosbag2-storage-mcap
      - ros-jazzy-std-msgs
      - ros-jazzy-sensor-msgs
      - ros-jazzy-geometry-msgs
      - ros-jazzy-nav-msgs
    override-build: |
      set -e

      # temporarily move rosbag_replayer
      if [ -d rosbag_replayer ]; then
        mv rosbag_replayer rosbag_replayer.component
      fi

      craftctl default

      if [ -d rosbag_replayer.component ]; then
        mv rosbag_replayer.component rosbag_replayer
      fi

      # make local venv with system packages
      python3 -m venv venv --system-site-packages
      source venv/bin/activate

      # install python deps into venv
      pip install -U reduct-py mcap mcap-ros2-support numpy

      # copy venv site-packages into snap stage
      cp -a venv/lib/python3.*/site-packages/* $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages/

  # Replayer component - files go into the 'replayer' component, not the main snap
  replayer:
    plugin: dump
    source: rosbag_replayer/
    organize:
      '*.py': (component/replayer)/usr/lib/python3/dist-packages/rosbag_replayer/

apps:
  recorder:
    command: usr/bin/run_recorder.sh
    daemon: simple
    extensions: [ros2-jazzy]
    plugs: [network, network-bind]
    environment:
      ROS_DOMAIN_ID: "0"
      ROS_AUTOMATIC_DISCOVERY_RANGE: "SUBNET"
      RCUTILS_COLORIZED_OUTPUT: "1"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

  rosbag-replayer:
    command: usr/bin/run_replayer.sh
    extensions: [ros2-jazzy]
    plugs: [network, network-bind, home]
    environment:
      ROS_DOMAIN_ID: "0"
      ROS_AUTOMATIC_DISCOVERY_RANGE: "SUBNET"
      RCUTILS_COLORIZED_OUTPUT: "1"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

  config-help:
    command: usr/bin/config_help.sh
    extensions: [ros2-jazzy]
