name: reductstore_agent CI

on:
  push:
    branches: [main]
    tags:
      - "v*"
    paths-ignore:
      - README.md
      - CHANGELOG.md

  pull_request:
    branches: [main]
    paths-ignore:
      - README.md
      - CHANGELOG.md

jobs:
  check-version-tag:
    name: Check Git Tag Matches package.xml
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Check tag matches version in package.xml
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          echo "Git tag is $TAG_NAME"

          PACKAGE_VERSION=$(xmllint --xpath "string(//version)" package.xml)
          echo "Version from package.xml is $PACKAGE_VERSION"

          if [ "v$PACKAGE_VERSION" != "$TAG_NAME" ]; then
            echo "❌ Tag $TAG_NAME does not match version in package.xml ($PACKAGE_VERSION)"
            exit 1
          fi

          echo "✅ Tag matches version in package.xml"

  format:
    name: Formatting Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install formatting tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Run Black
        run: black --check .

      - name: Run isort
        run: isort --check-only .

  ros2-tests:
    name: Build & Pytest (ROS ${{ matrix.ros_distro }}) with ReductStore
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ros_distro: [jazzy, rolling]

    services:
      reductstore:
        image: reduct/store:main
        ports:
          - 8383:8383

    steps:
      - uses: actions/checkout@v4

      - name: Run tests with ROS ${{ matrix.ros_distro }}
        uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: ${{ matrix.ros_distro }}
          ROS_REPO: main
          DOCKER_RUN_OPTS: "--network=host"
          ADDITIONAL_DEBS: >
            python3-pip
            ros-${{ matrix.ros_distro }}-sensor-msgs
            ros-${{ matrix.ros_distro }}-geometry-msgs
            ros-${{ matrix.ros_distro }}-rosbag2-py
          AFTER_INIT: |
            pip install --no-deps --ignore-installed --break-system-packages \
              pytest \
              pytest-cov \
              mcap \
              mcap-ros2-support \
              reduct-py
          AFTER_SCRIPT: |
            export COVERAGE_FILE=/tmp/.coverage
            rosenv pytest \
              --cov=/root/target_ws/install/reductstore_agent/lib/python3.12/site-packages/reductstore_agent \
              --cov-report=term \
              --cov-fail-under=90 \
              test/