name: ros2-reduct-agent CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Run Black
        run: black --check .

      - name: Run isort
        run: isort --check-only .

  ros2-tests:
    name: ROS 2 Build & Pytest (w/ ReductStore)
    runs-on: ubuntu-latest

    services:
      reductstore:
        image: reduct/store:main
        ports:
          - 8383:8383

    steps:
      - uses: actions/checkout@v4

      - name: Run industrial_ci
        uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: jazzy
          ROS_REPO: main
          ADDITIONAL_DEBS: python3-pip
          AFTER_INIT: |
            pip install --upgrade pip
            pip install pytest
          AFTER_SCRIPT: |
            source install/setup.bash
            pytest
          DOCKER_RUN_OPTS: "--network=host"
