name: ros2-reduct-agent CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Run Black
        run: black --check .

      - name: Run isort
        run: isort --check-only .

  ros2-tests:
    name: Build & Pytest (ROS 2 Jazzy) with ReductStore
    runs-on: ubuntu-latest

    services:
      reductstore:
        image: reduct/store:main
        ports:
          - 8383:8383

    steps:
      - uses: actions/checkout@v4

      - name: industrial_ci
        uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: jazzy
          ROS_REPO: main
          DOCKER_RUN_OPTS: "--network=host"
          ADDITIONAL_DEBS: "python3-venv"
          AFTER_INIT: |
            set -e
            python3 -m venv /tmp/ci_venv
            source /tmp/ci_venv/bin/activate
            pip install --upgrade pip
            pip install pytest
            # keep venv for later hooks
            echo 'source /tmp/ci_venv/bin/activate' >> /root/.bashrc
          AFTER_SCRIPT: |
            set -e
            source /tmp/ci_venv/bin/activate
            # `rosenv` sources /opt/ros/$ROS_DISTRO/setup.bash for us
            rosenv source install/setup.bash && pytest -v
