name: ros2-reduct-agent CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Run Black
        run: black --check .

      - name: Run isort
        run: isort --check-only .

  test:
    runs-on: ubuntu-latest
    services:
      reductstore:
        image: reduct/store:main
        ports:
          - 8383:8383

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up ROS 2 Jazzy
        uses: ika-rwth-aachen/docker-ros@main
        with:
          platform: amd64
          base-image: rwthika/ros2:jazzy
          target: dev
          command: echo "ROS ready"

      - name: Install dependencies and test tools
        run: |
          sudo apt update
          sudo apt install -y python3-pytest python3-colcon-common-extensions python3-pip
          pip3 install -U pip
          pip3 install pytest

      - name: Build ROS 2 package
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --packages-select ros2_reduct_agent

      - name: Run tests
        run: |
          source install/setup.bash
          pytest