name: ros2-reduct-agent CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Run Black
        run: black --check .

      - name: Run isort
        run: isort --check-only .

  test-python:
    name: Pytest for Recorder Logic
    runs-on: ubuntu-latest

    services:
      reductstore:
        image: reduct/store:main
        ports:
          - 8383:8383

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest rclpy

      - name: Run pytest
        run: |
          pytest

  ros2-smoke-test:
    name: Smoke Test Node Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: ika-rwth-aachen/docker-ros@v1.7.0
        with:
          base-image: rwthika/ros2:jazzy
          target: dev,run
          command: ros2 run ros2_reduct_agent ros2_reduct_agent
